cp ../chip1/sex.repl ./sex_1.repl
cp ../chip2/sex.repl ./sex_2.repl
cp ../chip3/sex.repl ./sex_3.repl
cp ../chip4/sex.repl ./sex_4.repl
cp ../chip5/sex.repl ./sex_5.repl
cp ../chip6/sex.repl ./sex_6.repl
cp ../chip7/sex.repl ./sex_7.repl
cp ../chip8/sex.repl ./sex_8.repl

cp ../chip1/chip1.mch .
cp ../chip1/chip1.tfr .
cp ../chip1/chip1.makemag .
cp ../chip2/chip2.mch .
cp ../chip2/chip2.tfr .
cp ../chip2/chip2.makemag .
cp ../chip3/chip3.mch .
cp ../chip3/chip3.tfr .
cp ../chip3/chip3.makemag .
cp ../chip4/chip4.mch .
cp ../chip4/chip4.tfr .
cp ../chip4/chip4.makemag .
cp ../chip5/chip5.mch .
cp ../chip5/chip5.tfr .
cp ../chip5/chip5.makemag .
cp ../chip6/chip6.mch .
cp ../chip6/chip6.tfr .
cp ../chip6/chip6.makemag .
cp ../chip7/chip7.mch .
cp ../chip7/chip7.tfr .
cp ../chip7/chip7.makemag .
cp ../chip8/chip8.mch .
cp ../chip8/chip8.tfr .
cp ../chip8/chip8.makemag .
